### ISSUE TITLE
Question: I wonder why the "Representation Enhancement" could be categorized as one of the models under the "Density Estimation with Deep Generative Models"?

### ISSUE THREAD

**Issue by WenxuanChelsea** [Jingkang50/OODSurvey#7]
Hi,

Really thanks for this super comprehensive survey, which really helped me get to the basic level of this area with a complete framework, and saved a lot of my time. I understood most of the paper but still got a few questions. I am curious about this question mostly: I wonder why the "Representation Enhancement" could be categorized as one of the models under the "Density Estimation with Deep Generative Models", what is the reason that leads you to put it as d part under 3.1.2?

**Comment by Jingkang50** [comment]
Thank you for the nice catch! It would be better to rename 3.1.2 with Density Estimation with Deep Models.

3.1.2 improves classic density-based methods (in 3.1.1) by using higher-quality features/representations extracted from deep learning models. While most deep learning-based methods in AD are DGM, some can also get better representations via other methods, and collected in 3.1.2-d. Therefore, 3.1.2-d should be complementary to DGM under deep learning category.

We will correct this when we update the manuscript. Thanks!
