### ISSUE TITLE
the topic "novety class discovery" is missing.

### ISSUE THREAD

**Issue by ACMMM2022anonymous** [Jingkang50/OODSurvey#9]
nice work. I notice that the topic about "novety class discovery" is missing. That is, sometimes it is not enough for the ood samples 
 are just recognized as class "ood", they also need to be specifically classified. I recommend that the authors could consider to add this part.

**Comment by Jingkang50** [comment]
Thank you for the comment. Actually, we introduce this set of work in section 2.6 novelty discovery part.
Your summary also looks good and I will revise this part in the next update accordingly. Thank you!
